### ISSUE TITLE
Update Checkout/Checkin APIs to handle errors with quantities

### ISSUE THREAD

**Issue by sidshyamkumar** [rohanjain65/17545-TBD#32]
Bugs with checkout/checkin:
- user checking in more HW than the project has checked out
- user checking out more hardware than the HW set has available

**Comment by rohanjain65** [comment]
Don't we also need to connect HWSet quantities to DB to grab existing availability?

**Comment by sidshyamkumar** [comment]
> Don't we also need to connect HWSet quantities to DB to grab existing availability?

Yes this was done in issue #23

**Comment by sidshyamkumar** [comment]
> Don't we also need to connect HWSet quantities to DB to grab existing availability?

I see what you mean now. I'll work this on this issue.

**Comment by sidshyamkumar** [comment]
Fixed in Issue #37
