### ISSUE TITLE
Update project tracking page to render based on joined projects

### ISSUE THREAD

**Issue by rohanjain65** [rohanjain65/17545-TBD#4]
- ability to open existing projects after you have signed in

**Comment by sidshyamkumar** [comment]
This issue expands on work done in Issue #12 . We need to update that work to render projects based on what projects this user is an authorized user of. Renaming issue to better match this.

**Comment by sidshyamkumar** [comment]
Will need a backend api to fetch all projects this user is a part of. Maybe break this up into two tickets if you'd like. Use localStorage.getItem("username"); to get this user. Example in NewProjectModal.js
