### ISSUE TITLE
Encryption/decryption for user passwords

### ISSUE THREAD

**Issue by AlexForlenza** [rohanjain65/17545-TBD#5]
Write a cryptography algorithm that encrypts and decrypts user passwords during the login process.

**Comment by jert924** [comment]
Could expand on the encryption/decryption functions we made for HW2. Perhaps make the encryption/decryption more complex than what we implemented for the HW

**Comment by sidshyamkumar** [comment]
Opting to stick with the encryption from the homework for initial simplicity. However, encryption/decryption will be modularized enough such that we can change the scheme without breaking our downstream frontend or backend.
